version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.eclipse.collections:eclipse-collections
        versions:
          - ">= 10.a"
      - dependency-name: org.eclipse.collections:eclipse-collections-api
        versions:
          - ">= 10.a"
      - dependency-name: org.jenkins-ci.plugins.workflow:workflow-basic-steps
        versions:
          - ">= 2.23"
      - dependency-name: org.jenkins-ci.plugins:git
        versions:
          - ">= 4.7.0"
      - dependency-name: org.jenkins-ci.plugins:git-client
        versions:
          - ">= 3.7.0"
      - dependency-name: org.jenkins-ci.main:maven-plugin
        versions:
          - "> 3.8"
      - dependency-name: org.jenkins-ci.plugins:token-macro
        versions:
          - "> 2.13"
      - dependency-name: org.webjars:popper.js
        versions:
          - ">= 2.0.0"
      - dependency-name: org.webjars:bootstrap
        versions:
          - ">= 5.0.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
