@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #a0a0a0
  BackgroundColor #f8f8f8
}

[Steps] <<..metrics.steps>>
[Color] <<..metrics.color>>
[Source] <<..metrics.source>>
[Charts] <<..metrics.charts>>
[Model] <<..metrics.model>>

[Steps] --> [Model]
[Steps] --> [Color]
[Steps] --> [Source]
[Steps] --> [Charts]

[Charts] --> [Color]
[Charts] --> [Model]

[Source] --> [Model]

[Model] --> [Color]


@enduml
